/*
 * Turn a rule spec (from the UI) into the source of a valid apigeelint plugin
 * module, ready to drop into cli/externalPlugins/.
 *
 * The full spec is embedded in a machine-readable banner comment so the rule
 * can be re-opened and edited later in the UI (round-trip).
 */
const { byId, NODE_TYPES } = require("./templates");

const SPEC_BANNER_OPEN = "/* @rule-studio:spec";
const SPEC_BANNER_CLOSE = "*/";

const LICENSE_HEADER = `/*
  Generated by apigeelint Rule Studio. Apache-2.0.

  This is an apigeelint plugin (a custom lint rule). It is loaded automatically
  by the bundled CLI. Do not hand-edit the @rule-studio:spec banner below; edit
  the rule in Rule Studio instead so the spec and the code stay in sync.
*/`;

function pascalCase(s) {
  return String(s || "rule")
    .replace(/[^a-zA-Z0-9 ]+/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("")
    .slice(0, 48) || "Rule";
}

// Resolve the effective nodeType: advanced rules choose it; templated rules
// inherit it from the template.
function nodeTypeFor(spec) {
  const tmpl = byId(spec.templateId);
  if (!tmpl) throw new Error(`unknown template: ${spec.templateId}`);
  return tmpl.advanced ? spec.nodeType || tmpl.nodeType : tmpl.nodeType;
}

function fileBaseName(spec) {
  // e.g. EX-PO050-RequireDisplayName
  return `${spec.ruleId}-${pascalCase(spec.name)}`;
}

function generatePlugin(spec) {
  const tmpl = byId(spec.templateId);
  if (!tmpl) throw new Error(`unknown template: ${spec.templateId}`);

  const nodeType = nodeTypeFor(spec);
  const meta = NODE_TYPES[nodeType];
  if (!meta) throw new Error(`unsupported nodeType: ${nodeType}`);

  const severity = [0, 1, 2].includes(Number(spec.severity)) ? Number(spec.severity) : 1;
  const enabled = spec.enabled !== false;

  const listenerBody = tmpl.build(spec.params || {});

  // Re-embed the canonical spec (with the resolved nodeType) for round-tripping.
  const embeddedSpec = {
    ruleId: spec.ruleId,
    name: spec.name,
    message: spec.message,
    severity,
    nodeType,
    enabled,
    templateId: spec.templateId,
    params: spec.params || {},
  };

  const code = `${LICENSE_HEADER}

${SPEC_BANNER_OPEN}
${JSON.stringify(embeddedSpec, null, 2)}
${SPEC_BANNER_CLOSE}

const plugin = {
  ruleId: ${JSON.stringify(spec.ruleId)},
  name: ${JSON.stringify(spec.name)},
  message: ${JSON.stringify(spec.message || spec.name)},
  fatal: false,
  severity: ${severity},
  nodeType: ${JSON.stringify(nodeType)},
  enabled: ${enabled},
};

const ${meta.listener} = function (${meta.arg}, cb) {
  let flagged = false;
  ${listenerBody}
  if (typeof cb === "function") {
    cb(null, flagged);
  }
};

module.exports = {
  plugin,
  ${meta.listener},
};
`;

  return { code, nodeType, listener: meta.listener };
}

// Pull the embedded spec back out of a generated plugin file (for editing).
function parseEmbeddedSpec(source) {
  const start = source.indexOf(SPEC_BANNER_OPEN);
  if (start === -1) return null;
  const from = start + SPEC_BANNER_OPEN.length;
  const end = source.indexOf(SPEC_BANNER_CLOSE, from);
  if (end === -1) return null;
  try {
    return JSON.parse(source.slice(from, end).trim());
  } catch {
    return null;
  }
}

module.exports = { generatePlugin, parseEmbeddedSpec, pascalCase, fileBaseName, nodeTypeFor };
